# Generated by Django 4.1.2 on 2023-03-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('segment_class', models.CharField(max_length=30)),
                ('segment', models.CharField(max_length=10)),
                ('marginal', models.BooleanField(null=True)),
                ('allophones', models.CharField(max_length=30, null=True)),
                ('representation_percentage', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
