# Generated by Django 4.1.2 on 2023-03-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_comparison', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonetics',
            old_name='representation_percentage',
            new_name='representation_percent',
        ),
        migrations.AlterField(
            model_name='phonetics',
            name='allophones',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='phonetics',
            name='marginal',
            field=models.BooleanField(default=False),
        ),
    ]
