# Generated by Django 4.1.2 on 2023-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_comparison', '0003_intersections_ipa_phonemes_audio_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipa_phonemes_audio_href',
            name='consonant_articulation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ipa_phonemes_audio_href',
            name='consonant_manner',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ipa_phonemes_audio_href',
            name='vowel_forward',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ipa_phonemes_audio_href',
            name='vowel_height',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
