# Generated by Django 4.1.2 on 2023-03-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang_comparison', '0004_alter_ipa_phonemes_audio_href_consonant_articulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetics',
            name='phoneme_desc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lang_comparison.ipa_phonemes_audio_href'),
        ),
    ]
