# Generated by Django 4.1.2 on 2023-03-21 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang_comparison', '0005_phonetics_phoneme_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang_geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('wals_code', models.CharField(max_length=5, null=True)),
                ('iso_639_3', models.CharField(max_length=5, null=True)),
                ('genus', models.CharField(max_length=30, null=True)),
                ('family', models.CharField(max_length=30)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('macroarea', models.IntegerField()),
                ('countries', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Lang_inventory_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.CharField(max_length=30)),
                ('num_segments', models.IntegerField()),
                ('num_vowels', models.IntegerField()),
                ('num_consonants', models.IntegerField()),
                ('num_tones', models.IntegerField()),
                ('contributor', models.CharField(max_length=30)),
                ('cite', models.CharField(max_length=30)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lang_comparison.lang_geography')),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=7)),
                ('value', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('feature', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lang_comparison.lang_geography')),
            ],
        ),
    ]
