# Generated by Django 4.1.2 on 2023-03-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang_comparison', '0006_lang_geography_lang_inventory_data_grammar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang_iso',
            fields=[
                ('iso_639_3', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('search_name_phoible', models.CharField(max_length=30)),
                ('phoible_lang', models.CharField(max_length=30)),
                ('wals_lang', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='lang_geography',
            old_name='name',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='phoneme_examples',
            name='language',
        ),
        migrations.AlterField(
            model_name='lang_geography',
            name='countries',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='lang_geography',
            name='family',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lang_geography',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lang_geography',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lang_geography',
            name='macroarea',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Lang_inventory_data',
        ),
        migrations.AddField(
            model_name='phoneme_examples',
            name='iso_639_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lang_comparison.lang_iso'),
        ),
        migrations.AlterField(
            model_name='lang_geography',
            name='iso_639_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lang_comparison.lang_iso'),
        ),
    ]
