# Generated by Django 4.1.2 on 2023-03-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_comparison', '0007_lang_iso_rename_name_lang_geography_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang_geography',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lang_geography',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lang_geography',
            name='macroarea',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
