# Generated by Django 4.1.2 on 2023-03-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang_comparison', '0008_alter_lang_geography_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='iso_639_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lang_comparison.lang_iso'),
        ),
        migrations.AddField(
            model_name='phonetics',
            name='iso_639_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lang_comparison.lang_iso'),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
