# Generated by Django 4.1.2 on 2023-04-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_comparison', '0009_grammar_iso_639_3_phonetics_iso_639_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='feature',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='reference',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
